#!/bin/bash
echo "Updating Javadocs for PartyChat"
git init
git remote add javadoc https://majekdor@github.com/majekdor/partychat.git
git fetch --depth=1 javadoc gh-pages
git add --all
git commit -m "Javadocs update"
git merge --no-edit --allow-unrelated-histories -s ours remotes/javadoc/gh-pages
git push javadoc master:gh-pages
